# Generated by Django 4.2.5 on 2023-09-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_song_spotify_link_song_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
