# Generated by Django 4.2.5 on 2023-09-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_place_lat_place_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='latest_song_uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
